# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "MD-Theme"
license = "MIT"
licenselink = "https://github.com/Tangyanxin/MD-Theme/LICENSE.md"
description = "A Material Design Theme for Hugo"
homepage = "inkbottle.site/MD-Theme/"
tags = ["Blog", "Theme", "Material Design"]
features = ["Responsive"]
min_version = "0.21"

[author]
  name = "inkbottle"
  homepage = "inkbottle.site"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
